### ISSUE TITLE
Unable to start Docker Container

### ISSUE THREAD

**Issue by saturnism** [openzipkin/docker-zipkin-gcp#2]
```
2018-07-25 01:49:59.558  WARN 7 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start web server; 
nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'zipkinServerConfiguration': Unsatisfied dependency expressed through field 'httpCollector'; 
nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'zipkinHttpCollector' defined in file [/zipkin/BOOT-INF/classes/zipkin/server/internal/ZipkinHttpCollector.class]: Unsatisfied dependency expressed through constructor parameter 0; 
nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'storage' defined in class path resource [zipkin/autoconfigure/storage/stackdriver/ZipkinStackdriverStorageAutoConfiguration.class]: Unsatisfied dependency expressed through method 'storage' parameter 2; 
nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'managedChannel' defined in class path resource [zipkin/autoconfigure/storage/stackdriver/ZipkinStackdriverStorageAutoConfiguration.class]: Bean instantiation via factory method failed; 
nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.grpc.ManagedChannel]: Factory method 'managedChannel' threw exception; nested exception is java.lang.IllegalStateException: OpenSsl required
```

**Comment by adriancole** [comment]
will take a look tomorrow first thing. missed it!

**Comment by saturnism** [comment]
Thanks! I was having trouble tracing back the container used. Is it using Alpine by any chance? If so.. that could explain the issue.

**Comment by adriancole** [comment]
we recently changed to normal openjdk...

**Comment by adriancole** [comment]
pushing image zipkin-gcp 0.7.0 now

**Comment by adriancole** [comment]
if you don't mind, can you q/a for me once it is on dockerhub? I am watching now, so if there's a problem i will see and dig

**Comment by saturnism** [comment]
i just gave 0.7.0 tag a try, but seeing the same issue. I think the base image is still alpine.

I haven't been able to trace the root base image:
```
FROM openzipkin/zipkin:2.11.1
...
RUN apk add unzip <- this still looks like alpine based distribution
...
```

**Comment by adriancole** [comment]
It is failing on OpenSsl required. Our base image for very long time has been alpine. Perhaps there's a package missing or something new in a later version of grpc that wasn't the case earlier

**Comment by adriancole** [comment]
I'm very much hoping that netty/netty-tcnative#111 isn't true and grpc isn't unsupported on alpine :P

@saturnism say it ain't so!

cc @openzipkin/devops-tooling

**Comment by saturnism** [comment]
afaik, it never supported alpine's libmusl :(
https://github.com/grpc/grpc-java/blob/master/SECURITY.md#troubleshooting <- I wrote most of this ;)

For smaller images, I'd recommend `openjdk:8-jre-slim`, or `gcr.io/distroless/java` :(

**Comment by adriancole** [comment]
maybe there was a fallback or something, unless somehow the image was never
tested which seems unlikely.

anyway you are saying we need a custom image huh. that sucks

**Comment by adriancole** [comment]
I dont think we want to change all of our images just because grpc uses
something that could but chooses not to support alpine.

what we can do here is copy the config from the base zipkin image, based on
one of the ones mentioned, and make a note about the drift risk.

if the SSL support really never supports alpine then this debt will
continue. ideally considering all the resources on grpc, someone will pitch
in and get alpine supported.

**Comment by saturnism** [comment]
Makes sense!

The other option is to add glibc to this image. but i don't think there is official support.

In the past we had a stackdriver zipkin proxy image that was hosted on `gcr.io`. That one worked for sure.

Thanks for taking a look!

**Comment by adriancole** [comment]
one of the things I believe google should be doing while promoting gcp is doing more to help norman. For example, this PR could have gotten alpine.. when there's a surge of demand on projects like netty, it could be good to dig in and help https://github.com/netty/netty-tcnative/pull/252

if that happened, we'd probably have no dillemma right now, but there's still a chance to change the future :) @saturnism can you take this feedback to google? :P

**Comment by adriancole** [comment]
opened https://github.com/openzipkin/docker-jre-full/issues/9 to track us moving our base image to JRE 11, which will obviate the ssl concern

**Comment by adriancole** [comment]
zipkin-gcp 0.6.2 works, it started crashing in 0.6.3

**Comment by adriancole** [comment]
so this happened when we upgraded from grpc 1.11.0 to 1.13.1. One way out is to revert that.. this is the easiest. then we just upgrade later

**Comment by adriancole** [comment]
<img width="895" alt="screen shot 2018-08-09 at 1 33 00 pm" src="https://user-images.githubusercontent.com/64215/43878180-c3729b20-9bd8-11e8-9dff-9823650bcde7.png">

so this is from the 0.6.2 image

**Comment by adriancole** [comment]
checking to see if this is related to us changing to a different alpine image, which is entirely possible

**Comment by adriancole** [comment]
ok we are getting somewhere.. our base zipkin image switch from zulu to openjdk jre (both alpine) starting with zipkin 2.9.4.

Must be that the zulu image had openssl else the error would have occurred much earlier
https://github.com/openzipkin/zipkin-gcp/blob/master/autoconfigure/storage-stackdriver/src/main/java/zipkin/autoconfigure/storage/stackdriver/ZipkinStackdriverStorageAutoConfiguration.java#L83

**Comment by adriancole** [comment]
so the original image depended on, so this is why it worked https://hub.docker.com/r/frolvlad/alpine-glibc/~/dockerfile/

**Comment by adriancole** [comment]
ok 0.7.1 should fix this. thanks especially @anuraaga for helping find a way out of this problem without implying lot of temporary image reshuffling.

**Comment by adriancole** [comment]
tested published image, so hopefully also works for others!

**Comment by saturnism** [comment]
Yay! That started off fine. Thank you!
