### ISSUE TITLE
Does not forward anything to Stackdriver Trace from GKE.

### ISSUE THREAD

**Issue by yehudamakarov** [openzipkin/docker-zipkin-gcp#8]
When I run the docker command 
```
docker run -d -p 9411:9411 \ 
-e STORAGE_TYPE=stackdriver \
-e GOOGLE_APPLICATION_CREDENTIALS=/var/secret/google/key.json \
-e STACKDRIVER_PROJECT_ID=<ID> \
-v $HOME/Desktop/googleKeys:/var/secret/google openzipkin/zipkin-gcp
```
I successfully start the image and see logs for the zipkin server. But I only see a 404, when i visit the host/port of the server in the browser.

In the regular zipkin docker image I see the web UI. Acutally `/` reroutes to `/zipkin` which serves the UI.

I'm really running this as a deployment behind a service in GKE, and nothing is being forwarded to Trace. Looking for a way to debug.

**Comment by adriancole** [comment]
The stackdriver integration is write-only at the moment, which is why you
don't see zipkin's UI. Are you intentionally interested in using Zipkin's
UI instead of stackdriver's?

**Comment by yehudamakarov** [comment]
That's REALLY helpful to know. thank you. No i actually don't need UI at all. But no traces are making it into stackdriver, and I'm not sure how to start trouble shooting. 

I followed https://kubernetes.github.io/ingress-nginx/user-guide/third-party-addons/opentracing/ for the most part.

I expected that like the example there, just enabling the module and providing the service name of the zipkin service (that points to my deployment) would be enough to see traces in stackdriver.

Is there another way to check whether the zipkin pod is receiving any trace data?

**Comment by adriancole** [comment]
you can use our prometheus/grafana setup. or even ad-hoc look at the
/metrics endpoint

https://github.com/openzipkin/docker-zipkin/blob/master/docker-compose.yml

**Comment by yehudamakarov** [comment]
Epic! thank you!
So now I'll redeploy my collector and service, and check the metrics endpoint. 
I guess if I'm not receiving anything from the sender, that would mean this is an issue with the ingress-nginx `enable-opentracing` in the configMap. Thank you for your help.

**Comment by adriancole** [comment]
no worries good luck!
